<?php

namespace AppBundle\Repository;

use \DateTime;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSorted()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.publication', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function findAllFutur()
    {
        return $this->createQueryBuilder('a')
            ->where('a.publication > :publication')
            ->setParameter('publication', new DateTime())
            ->orderBy('a.publication', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * Renvoie la liste des articles publiés, triée par date de publication et par nom d'auteur
     */
    public function findAllPublieSortedByDateAndAuteurNom()
    {
        return $this->createQueryBuilder('a')
            ->innerJoin('a.auteur', 'aut')
            ->where('a.publie = :publie')
            ->setParameter('publie', true)
            ->addOrderBy('a.publication', 'DESC')
            ->addOrderBy('aut.nom', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * Renvoie la liste des articles non publiés, triée par date de publication et par nom d'auteur
     */
    public function findAllNonPublieSortedByDateAndAuteurNom()
    {
        return $this->createQueryBuilder('a')
            ->innerJoin('a.auteur', 'aut')
            ->where('a.publie = :publie')
            ->setParameter('publie', false)
            ->addOrderBy('a.publication', 'DESC')
            ->addOrderBy('aut.nom', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
