<?php

namespace AppBundle\Repository;

use \DateTime;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllSorted()
    {
        return $this->createQueryBuilder('a')
            ->orderBy('a.publication', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function findAllFutur()
    {
        return $this->createQueryBuilder('a')
            ->where('a.publication > :publication')
            ->setParameter('publication', new DateTime())
            ->orderBy('a.publication', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
